# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from animal_classifier_server.models.base_model_ import Model
from animal_classifier_server import util


class Classification(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None, confidence=None):  # noqa: E501
        """Classification - a model defined in OpenAPI

        :param result: The result of this Classification.  # noqa: E501
        :type result: str
        :param confidence: The confidence of this Classification.  # noqa: E501
        :type confidence: float
        """
        self.openapi_types = {
            'result': str,
            'confidence': float
        }

        self.attribute_map = {
            'result': 'result',
            'confidence': 'confidence'
        }

        self._result = result
        self._confidence = confidence

    @classmethod
    def from_dict(cls, dikt) -> 'Classification':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Classification of this Classification.  # noqa: E501
        :rtype: Classification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self):
        """Gets the result of this Classification.


        :return: The result of this Classification.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this Classification.


        :param result: The result of this Classification.
        :type result: str
        """

        self._result = result

    @property
    def confidence(self):
        """Gets the confidence of this Classification.


        :return: The confidence of this Classification.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this Classification.


        :param confidence: The confidence of this Classification.
        :type confidence: float
        """

        self._confidence = confidence
