version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
      - 9001:9001
    command: mosquitto -c /mosquitto-no-auth.conf
  mongo:
    image: mongo
    ports:
    - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: random